# SPDX-FileCopyrightText: 2024 Gerald Wiese
#
# SPDX-License-Identifier: GPL-3.0-or-later

steps:
  test:
    image: gnuhealth/linter:1.0.1
    pull: true
    commands:
      - bash scripts/lint.sh
      - bash scripts/security.sh

