# SPDX-FileCopyrightText: 2024 Gerald Wiese
#
# SPDX-License-Identifier: GPL-3.0-or-later

steps:
  - name: test
    image: gnuhealth/linter:1.0.1
    commands:
      - bash scripts/lint.sh
      # - bash scripts/security.sh
      # - bash scripts/test_modules.sh
    when:
      - event: [push, pull_request, cron, manual]


deploy-his-git:
   image: appleboy/drone-git-push
   settings:
     path: tmp/his-git
     remote: git@codeberg.org:gnuhealth/his.git
     ssh_key:
       from_secret: ssh_deploy_key

     branch: translate-ci
     force: true
     commit: true
     commit_message: "Update po files with Woodpecker CI"

