# SPDX-FileCopyrightText: 2024 Gerald Wiese
#
# SPDX-License-Identifier: GPL-3.0-or-later

# woodpecker syntax: https://woodpecker-ci.org/docs/usage/workflow-syntax

steps:

  his-git-code-check:
    image: gnuhealth/linter:1.0.1
    commands:
      - bash scripts/lint.sh
      # - bash scripts/security.sh
      # - bash scripts/test_modules.sh
    when:
      - branch:
          include: [main, dev-5.0, wip-*]
          exclude: [translate]
        event: [push, pull_request, manual]


  clone-his-utils-git:
    image: woodpeckerci/plugin-git
    settings:
      remote: https://codeberg.org/gnuhealth/his-utils.git
      branch: dev-5.0
      path: tmp/his-utils-git
      sha: ''
      ref: 'refs/heads/dev-5.0'
      partial: true
      lfs: false
    when:
      - branch: [dev-5.0, translate]
        event: [push, manual]


  clone-his-git:
    image: woodpeckerci/plugin-git
    settings:
      remote: https://codeberg.org/gnuhealth/his.git
      branch: dev-5.0
      path: tmp/his-git
      sha: ''
      ref: 'refs/heads/dev-5.0'
      partial: false
      lfs: false
    when:
      - branch: [dev-5.0, translate]
        event: [push, manual]


  run-po-export-script:
    image: debian
    commands:
      - apt-get update -y
      # installing packages in woodpecker of codeberg.org is very
      # slow, so just install packages necessary.
      - apt-get install -y --no-install-recommends --no-upgrade sqlite3 patch python3-pip python3-venv python3-dev gcc libsasl2-dev libldap2-dev git gettext libmagic1
      - git config --global user.email "po-export@po-export.invalid"
      - git config --global user.name "po-export"
      # We git clone his.git and his-utils.git to 'tmp' directory.
      - cd tmp
      # Install gnuhealth with the help of devel-installer in his-utils repo.
      - his-utils-git/devel-installer/devel-installer.sh --git-repo his-git --install-dir ghis --sqlite-db po-export-db
      # NOTE: if we do not use --fast-export argument, po-export.sh in
      # woodpecker will run > 1 hour, then fail for context deadline
      # exceeded reason, so if we change some packages with big xml
      # data files, for example health_gene*, we should run
      # po-export.sh in our own machine without --fast-export
      # argument.
      - ghis/ghis_env his-utils-git/scripts/po-export/update-his-repo.sh his-git --use-sqlite --database po-export-db --fast-export
    when:
      - branch: [dev-5.0, translate]
        event: [push, manual]


  push-po-changes-to-his-translate-branch:
    image: appleboy/drone-git-push
    settings:
      path: tmp/his-git
      remote: git@codeberg.org:gnuhealth/his.git
      ssh_key:
        from_secret: ssh_deploy_key
      branch: translate
      force: false
      commit: false
    when:
      - branch: [dev-5.0, translate]
        event: [push, manual]


  push-po-changes-to-his-dev-branch:
    image: appleboy/drone-git-push
    settings:
      path: tmp/his-git
      remote: git@codeberg.org:gnuhealth/his.git
      ssh_key:
        from_secret: ssh_deploy_key
      branch: dev-5.0
      force: false
      commit: false
    when:
      - branch: [dev-5.0, translate]
        event: [push, manual]
